url: "https://digitalnatives.iut.u-bordeaux-montaigne.fr/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
lang: "fr"

defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:slug
      layout: "default"




collections:
  pages:
    output: true

  years:
    output: true
    permalink: /:year/:name



plugins:
  - jekyll-redirect-from

disable_disk_cache: true
